PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: "6-gcc6.2-llvm3.7"

params:
  GPHOME_OLD:
  GPHOME_NEW:

inputs:
- name: terraform
- name: ccp_src
- name: cluster_env_files
- name: gpupgrade_src
  path: go/src/github.com/greenplum-db/gpupgrade
- name: gpdb_src
- name: bin_gpdb
- name: sqldump

run:
  path: go/src/github.com/greenplum-db/gpupgrade/ci/scripts/cluster-upgrade.bash
