// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub_to_agent.proto

package idl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpgradePrimariesRequest struct {
	OldBinDir            string         `protobuf:"bytes,1,opt,name=OldBinDir" json:"OldBinDir,omitempty"`
	NewBinDir            string         `protobuf:"bytes,2,opt,name=NewBinDir" json:"NewBinDir,omitempty"`
	NewVersion           string         `protobuf:"bytes,3,opt,name=NewVersion" json:"NewVersion,omitempty"`
	DataDirPairs         []*DataDirPair `protobuf:"bytes,4,rep,name=DataDirPairs" json:"DataDirPairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpgradePrimariesRequest) Reset()         { *m = UpgradePrimariesRequest{} }
func (m *UpgradePrimariesRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradePrimariesRequest) ProtoMessage()    {}
func (*UpgradePrimariesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{0}
}
func (m *UpgradePrimariesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradePrimariesRequest.Unmarshal(m, b)
}
func (m *UpgradePrimariesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradePrimariesRequest.Marshal(b, m, deterministic)
}
func (dst *UpgradePrimariesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradePrimariesRequest.Merge(dst, src)
}
func (m *UpgradePrimariesRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradePrimariesRequest.Size(m)
}
func (m *UpgradePrimariesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradePrimariesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradePrimariesRequest proto.InternalMessageInfo

func (m *UpgradePrimariesRequest) GetOldBinDir() string {
	if m != nil {
		return m.OldBinDir
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetNewBinDir() string {
	if m != nil {
		return m.NewBinDir
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetNewVersion() string {
	if m != nil {
		return m.NewVersion
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetDataDirPairs() []*DataDirPair {
	if m != nil {
		return m.DataDirPairs
	}
	return nil
}

type DataDirPair struct {
	OldDataDir           string   `protobuf:"bytes,1,opt,name=OldDataDir" json:"OldDataDir,omitempty"`
	NewDataDir           string   `protobuf:"bytes,2,opt,name=NewDataDir" json:"NewDataDir,omitempty"`
	OldPort              int32    `protobuf:"varint,3,opt,name=OldPort" json:"OldPort,omitempty"`
	NewPort              int32    `protobuf:"varint,4,opt,name=NewPort" json:"NewPort,omitempty"`
	Content              int32    `protobuf:"varint,5,opt,name=Content" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataDirPair) Reset()         { *m = DataDirPair{} }
func (m *DataDirPair) String() string { return proto.CompactTextString(m) }
func (*DataDirPair) ProtoMessage()    {}
func (*DataDirPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{1}
}
func (m *DataDirPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataDirPair.Unmarshal(m, b)
}
func (m *DataDirPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataDirPair.Marshal(b, m, deterministic)
}
func (dst *DataDirPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataDirPair.Merge(dst, src)
}
func (m *DataDirPair) XXX_Size() int {
	return xxx_messageInfo_DataDirPair.Size(m)
}
func (m *DataDirPair) XXX_DiscardUnknown() {
	xxx_messageInfo_DataDirPair.DiscardUnknown(m)
}

var xxx_messageInfo_DataDirPair proto.InternalMessageInfo

func (m *DataDirPair) GetOldDataDir() string {
	if m != nil {
		return m.OldDataDir
	}
	return ""
}

func (m *DataDirPair) GetNewDataDir() string {
	if m != nil {
		return m.NewDataDir
	}
	return ""
}

func (m *DataDirPair) GetOldPort() int32 {
	if m != nil {
		return m.OldPort
	}
	return 0
}

func (m *DataDirPair) GetNewPort() int32 {
	if m != nil {
		return m.NewPort
	}
	return 0
}

func (m *DataDirPair) GetContent() int32 {
	if m != nil {
		return m.Content
	}
	return 0
}

type UpgradePrimariesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradePrimariesReply) Reset()         { *m = UpgradePrimariesReply{} }
func (m *UpgradePrimariesReply) String() string { return proto.CompactTextString(m) }
func (*UpgradePrimariesReply) ProtoMessage()    {}
func (*UpgradePrimariesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{2}
}
func (m *UpgradePrimariesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradePrimariesReply.Unmarshal(m, b)
}
func (m *UpgradePrimariesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradePrimariesReply.Marshal(b, m, deterministic)
}
func (dst *UpgradePrimariesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradePrimariesReply.Merge(dst, src)
}
func (m *UpgradePrimariesReply) XXX_Size() int {
	return xxx_messageInfo_UpgradePrimariesReply.Size(m)
}
func (m *UpgradePrimariesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradePrimariesReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradePrimariesReply proto.InternalMessageInfo

type CheckUpgradeStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUpgradeStatusRequest) Reset()         { *m = CheckUpgradeStatusRequest{} }
func (m *CheckUpgradeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUpgradeStatusRequest) ProtoMessage()    {}
func (*CheckUpgradeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{3}
}
func (m *CheckUpgradeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUpgradeStatusRequest.Unmarshal(m, b)
}
func (m *CheckUpgradeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUpgradeStatusRequest.Marshal(b, m, deterministic)
}
func (dst *CheckUpgradeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUpgradeStatusRequest.Merge(dst, src)
}
func (m *CheckUpgradeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUpgradeStatusRequest.Size(m)
}
func (m *CheckUpgradeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUpgradeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUpgradeStatusRequest proto.InternalMessageInfo

type CheckUpgradeStatusReply struct {
	ProcessList          string   `protobuf:"bytes,1,opt,name=ProcessList" json:"ProcessList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUpgradeStatusReply) Reset()         { *m = CheckUpgradeStatusReply{} }
func (m *CheckUpgradeStatusReply) String() string { return proto.CompactTextString(m) }
func (*CheckUpgradeStatusReply) ProtoMessage()    {}
func (*CheckUpgradeStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{4}
}
func (m *CheckUpgradeStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUpgradeStatusReply.Unmarshal(m, b)
}
func (m *CheckUpgradeStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUpgradeStatusReply.Marshal(b, m, deterministic)
}
func (dst *CheckUpgradeStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUpgradeStatusReply.Merge(dst, src)
}
func (m *CheckUpgradeStatusReply) XXX_Size() int {
	return xxx_messageInfo_CheckUpgradeStatusReply.Size(m)
}
func (m *CheckUpgradeStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUpgradeStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUpgradeStatusReply proto.InternalMessageInfo

func (m *CheckUpgradeStatusReply) GetProcessList() string {
	if m != nil {
		return m.ProcessList
	}
	return ""
}

type CheckConversionStatusRequest struct {
	Segments             []*SegmentInfo `protobuf:"bytes,1,rep,name=Segments" json:"Segments,omitempty"`
	Hostname             string         `protobuf:"bytes,2,opt,name=Hostname" json:"Hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CheckConversionStatusRequest) Reset()         { *m = CheckConversionStatusRequest{} }
func (m *CheckConversionStatusRequest) String() string { return proto.CompactTextString(m) }
func (*CheckConversionStatusRequest) ProtoMessage()    {}
func (*CheckConversionStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{5}
}
func (m *CheckConversionStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckConversionStatusRequest.Unmarshal(m, b)
}
func (m *CheckConversionStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckConversionStatusRequest.Marshal(b, m, deterministic)
}
func (dst *CheckConversionStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckConversionStatusRequest.Merge(dst, src)
}
func (m *CheckConversionStatusRequest) XXX_Size() int {
	return xxx_messageInfo_CheckConversionStatusRequest.Size(m)
}
func (m *CheckConversionStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckConversionStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckConversionStatusRequest proto.InternalMessageInfo

func (m *CheckConversionStatusRequest) GetSegments() []*SegmentInfo {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *CheckConversionStatusRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type SegmentInfo struct {
	Content              int32    `protobuf:"varint,1,opt,name=Content" json:"Content,omitempty"`
	Dbid                 int32    `protobuf:"varint,2,opt,name=Dbid" json:"Dbid,omitempty"`
	DataDir              string   `protobuf:"bytes,3,opt,name=DataDir" json:"DataDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentInfo) Reset()         { *m = SegmentInfo{} }
func (m *SegmentInfo) String() string { return proto.CompactTextString(m) }
func (*SegmentInfo) ProtoMessage()    {}
func (*SegmentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{6}
}
func (m *SegmentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentInfo.Unmarshal(m, b)
}
func (m *SegmentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentInfo.Marshal(b, m, deterministic)
}
func (dst *SegmentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentInfo.Merge(dst, src)
}
func (m *SegmentInfo) XXX_Size() int {
	return xxx_messageInfo_SegmentInfo.Size(m)
}
func (m *SegmentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentInfo proto.InternalMessageInfo

func (m *SegmentInfo) GetContent() int32 {
	if m != nil {
		return m.Content
	}
	return 0
}

func (m *SegmentInfo) GetDbid() int32 {
	if m != nil {
		return m.Dbid
	}
	return 0
}

func (m *SegmentInfo) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

type CheckConversionStatusReply struct {
	Statuses             []*PrimaryStatus `protobuf:"bytes,1,rep,name=Statuses" json:"Statuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CheckConversionStatusReply) Reset()         { *m = CheckConversionStatusReply{} }
func (m *CheckConversionStatusReply) String() string { return proto.CompactTextString(m) }
func (*CheckConversionStatusReply) ProtoMessage()    {}
func (*CheckConversionStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{7}
}
func (m *CheckConversionStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckConversionStatusReply.Unmarshal(m, b)
}
func (m *CheckConversionStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckConversionStatusReply.Marshal(b, m, deterministic)
}
func (dst *CheckConversionStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckConversionStatusReply.Merge(dst, src)
}
func (m *CheckConversionStatusReply) XXX_Size() int {
	return xxx_messageInfo_CheckConversionStatusReply.Size(m)
}
func (m *CheckConversionStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckConversionStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckConversionStatusReply proto.InternalMessageInfo

func (m *CheckConversionStatusReply) GetStatuses() []*PrimaryStatus {
	if m != nil {
		return m.Statuses
	}
	return nil
}

type CreateSegmentDataDirRequest struct {
	Datadirs             []string `protobuf:"bytes,1,rep,name=datadirs" json:"datadirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSegmentDataDirRequest) Reset()         { *m = CreateSegmentDataDirRequest{} }
func (m *CreateSegmentDataDirRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSegmentDataDirRequest) ProtoMessage()    {}
func (*CreateSegmentDataDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{8}
}
func (m *CreateSegmentDataDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Unmarshal(m, b)
}
func (m *CreateSegmentDataDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSegmentDataDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSegmentDataDirRequest.Merge(dst, src)
}
func (m *CreateSegmentDataDirRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Size(m)
}
func (m *CreateSegmentDataDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSegmentDataDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSegmentDataDirRequest proto.InternalMessageInfo

func (m *CreateSegmentDataDirRequest) GetDatadirs() []string {
	if m != nil {
		return m.Datadirs
	}
	return nil
}

type CreateSegmentDataDirReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSegmentDataDirReply) Reset()         { *m = CreateSegmentDataDirReply{} }
func (m *CreateSegmentDataDirReply) String() string { return proto.CompactTextString(m) }
func (*CreateSegmentDataDirReply) ProtoMessage()    {}
func (*CreateSegmentDataDirReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{9}
}
func (m *CreateSegmentDataDirReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSegmentDataDirReply.Unmarshal(m, b)
}
func (m *CreateSegmentDataDirReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSegmentDataDirReply.Marshal(b, m, deterministic)
}
func (dst *CreateSegmentDataDirReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSegmentDataDirReply.Merge(dst, src)
}
func (m *CreateSegmentDataDirReply) XXX_Size() int {
	return xxx_messageInfo_CreateSegmentDataDirReply.Size(m)
}
func (m *CreateSegmentDataDirReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSegmentDataDirReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSegmentDataDirReply proto.InternalMessageInfo

type CopyMasterDirRequest struct {
	MasterDir            string   `protobuf:"bytes,1,opt,name=masterDir" json:"masterDir,omitempty"`
	Datadirs             []string `protobuf:"bytes,2,rep,name=datadirs" json:"datadirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyMasterDirRequest) Reset()         { *m = CopyMasterDirRequest{} }
func (m *CopyMasterDirRequest) String() string { return proto.CompactTextString(m) }
func (*CopyMasterDirRequest) ProtoMessage()    {}
func (*CopyMasterDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{10}
}
func (m *CopyMasterDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyMasterDirRequest.Unmarshal(m, b)
}
func (m *CopyMasterDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyMasterDirRequest.Marshal(b, m, deterministic)
}
func (dst *CopyMasterDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyMasterDirRequest.Merge(dst, src)
}
func (m *CopyMasterDirRequest) XXX_Size() int {
	return xxx_messageInfo_CopyMasterDirRequest.Size(m)
}
func (m *CopyMasterDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyMasterDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyMasterDirRequest proto.InternalMessageInfo

func (m *CopyMasterDirRequest) GetMasterDir() string {
	if m != nil {
		return m.MasterDir
	}
	return ""
}

func (m *CopyMasterDirRequest) GetDatadirs() []string {
	if m != nil {
		return m.Datadirs
	}
	return nil
}

type CopyMasterDirReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyMasterDirReply) Reset()         { *m = CopyMasterDirReply{} }
func (m *CopyMasterDirReply) String() string { return proto.CompactTextString(m) }
func (*CopyMasterDirReply) ProtoMessage()    {}
func (*CopyMasterDirReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{11}
}
func (m *CopyMasterDirReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyMasterDirReply.Unmarshal(m, b)
}
func (m *CopyMasterDirReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyMasterDirReply.Marshal(b, m, deterministic)
}
func (dst *CopyMasterDirReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyMasterDirReply.Merge(dst, src)
}
func (m *CopyMasterDirReply) XXX_Size() int {
	return xxx_messageInfo_CopyMasterDirReply.Size(m)
}
func (m *CopyMasterDirReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyMasterDirReply.DiscardUnknown(m)
}

var xxx_messageInfo_CopyMasterDirReply proto.InternalMessageInfo

type StopAgentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAgentRequest) Reset()         { *m = StopAgentRequest{} }
func (m *StopAgentRequest) String() string { return proto.CompactTextString(m) }
func (*StopAgentRequest) ProtoMessage()    {}
func (*StopAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{12}
}
func (m *StopAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAgentRequest.Unmarshal(m, b)
}
func (m *StopAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAgentRequest.Marshal(b, m, deterministic)
}
func (dst *StopAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAgentRequest.Merge(dst, src)
}
func (m *StopAgentRequest) XXX_Size() int {
	return xxx_messageInfo_StopAgentRequest.Size(m)
}
func (m *StopAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopAgentRequest proto.InternalMessageInfo

type StopAgentReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAgentReply) Reset()         { *m = StopAgentReply{} }
func (m *StopAgentReply) String() string { return proto.CompactTextString(m) }
func (*StopAgentReply) ProtoMessage()    {}
func (*StopAgentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_to_agent_8d1ee2dffad95038, []int{13}
}
func (m *StopAgentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAgentReply.Unmarshal(m, b)
}
func (m *StopAgentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAgentReply.Marshal(b, m, deterministic)
}
func (dst *StopAgentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAgentReply.Merge(dst, src)
}
func (m *StopAgentReply) XXX_Size() int {
	return xxx_messageInfo_StopAgentReply.Size(m)
}
func (m *StopAgentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAgentReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopAgentReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UpgradePrimariesRequest)(nil), "idl.UpgradePrimariesRequest")
	proto.RegisterType((*DataDirPair)(nil), "idl.DataDirPair")
	proto.RegisterType((*UpgradePrimariesReply)(nil), "idl.UpgradePrimariesReply")
	proto.RegisterType((*CheckUpgradeStatusRequest)(nil), "idl.CheckUpgradeStatusRequest")
	proto.RegisterType((*CheckUpgradeStatusReply)(nil), "idl.CheckUpgradeStatusReply")
	proto.RegisterType((*CheckConversionStatusRequest)(nil), "idl.CheckConversionStatusRequest")
	proto.RegisterType((*SegmentInfo)(nil), "idl.SegmentInfo")
	proto.RegisterType((*CheckConversionStatusReply)(nil), "idl.CheckConversionStatusReply")
	proto.RegisterType((*CreateSegmentDataDirRequest)(nil), "idl.CreateSegmentDataDirRequest")
	proto.RegisterType((*CreateSegmentDataDirReply)(nil), "idl.CreateSegmentDataDirReply")
	proto.RegisterType((*CopyMasterDirRequest)(nil), "idl.CopyMasterDirRequest")
	proto.RegisterType((*CopyMasterDirReply)(nil), "idl.CopyMasterDirReply")
	proto.RegisterType((*StopAgentRequest)(nil), "idl.StopAgentRequest")
	proto.RegisterType((*StopAgentReply)(nil), "idl.StopAgentReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Agent service

type AgentClient interface {
	CheckUpgradeStatus(ctx context.Context, in *CheckUpgradeStatusRequest, opts ...grpc.CallOption) (*CheckUpgradeStatusReply, error)
	CheckConversionStatus(ctx context.Context, in *CheckConversionStatusRequest, opts ...grpc.CallOption) (*CheckConversionStatusReply, error)
	CheckDiskSpace(ctx context.Context, in *CheckDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error)
	AgentExecuteUpgradePrimariesSubStep(ctx context.Context, in *UpgradePrimariesRequest, opts ...grpc.CallOption) (*UpgradePrimariesReply, error)
	CreateSegmentDataDirectories(ctx context.Context, in *CreateSegmentDataDirRequest, opts ...grpc.CallOption) (*CreateSegmentDataDirReply, error)
	CopyMasterDirectoryToSegmentDirectories(ctx context.Context, in *CopyMasterDirRequest, opts ...grpc.CallOption) (*CopyMasterDirReply, error)
	StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentReply, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) CheckUpgradeStatus(ctx context.Context, in *CheckUpgradeStatusRequest, opts ...grpc.CallOption) (*CheckUpgradeStatusReply, error) {
	out := new(CheckUpgradeStatusReply)
	err := grpc.Invoke(ctx, "/idl.Agent/CheckUpgradeStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CheckConversionStatus(ctx context.Context, in *CheckConversionStatusRequest, opts ...grpc.CallOption) (*CheckConversionStatusReply, error) {
	out := new(CheckConversionStatusReply)
	err := grpc.Invoke(ctx, "/idl.Agent/CheckConversionStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CheckDiskSpace(ctx context.Context, in *CheckDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error) {
	out := new(CheckDiskSpaceReply)
	err := grpc.Invoke(ctx, "/idl.Agent/CheckDiskSpace", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AgentExecuteUpgradePrimariesSubStep(ctx context.Context, in *UpgradePrimariesRequest, opts ...grpc.CallOption) (*UpgradePrimariesReply, error) {
	out := new(UpgradePrimariesReply)
	err := grpc.Invoke(ctx, "/idl.Agent/AgentExecuteUpgradePrimariesSubStep", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CreateSegmentDataDirectories(ctx context.Context, in *CreateSegmentDataDirRequest, opts ...grpc.CallOption) (*CreateSegmentDataDirReply, error) {
	out := new(CreateSegmentDataDirReply)
	err := grpc.Invoke(ctx, "/idl.Agent/CreateSegmentDataDirectories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CopyMasterDirectoryToSegmentDirectories(ctx context.Context, in *CopyMasterDirRequest, opts ...grpc.CallOption) (*CopyMasterDirReply, error) {
	out := new(CopyMasterDirReply)
	err := grpc.Invoke(ctx, "/idl.Agent/CopyMasterDirectoryToSegmentDirectories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentReply, error) {
	out := new(StopAgentReply)
	err := grpc.Invoke(ctx, "/idl.Agent/StopAgent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Agent service

type AgentServer interface {
	CheckUpgradeStatus(context.Context, *CheckUpgradeStatusRequest) (*CheckUpgradeStatusReply, error)
	CheckConversionStatus(context.Context, *CheckConversionStatusRequest) (*CheckConversionStatusReply, error)
	CheckDiskSpace(context.Context, *CheckDiskSpaceRequest) (*CheckDiskSpaceReply, error)
	AgentExecuteUpgradePrimariesSubStep(context.Context, *UpgradePrimariesRequest) (*UpgradePrimariesReply, error)
	CreateSegmentDataDirectories(context.Context, *CreateSegmentDataDirRequest) (*CreateSegmentDataDirReply, error)
	CopyMasterDirectoryToSegmentDirectories(context.Context, *CopyMasterDirRequest) (*CopyMasterDirReply, error)
	StopAgent(context.Context, *StopAgentRequest) (*StopAgentReply, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_CheckUpgradeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUpgradeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CheckUpgradeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CheckUpgradeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CheckUpgradeStatus(ctx, req.(*CheckUpgradeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CheckConversionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckConversionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CheckConversionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CheckConversionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CheckConversionStatus(ctx, req.(*CheckConversionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CheckDiskSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDiskSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CheckDiskSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CheckDiskSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CheckDiskSpace(ctx, req.(*CheckDiskSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AgentExecuteUpgradePrimariesSubStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradePrimariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AgentExecuteUpgradePrimariesSubStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/AgentExecuteUpgradePrimariesSubStep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AgentExecuteUpgradePrimariesSubStep(ctx, req.(*UpgradePrimariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CreateSegmentDataDirectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSegmentDataDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateSegmentDataDirectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CreateSegmentDataDirectories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateSegmentDataDirectories(ctx, req.(*CreateSegmentDataDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CopyMasterDirectoryToSegmentDirectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyMasterDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CopyMasterDirectoryToSegmentDirectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CopyMasterDirectoryToSegmentDirectories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CopyMasterDirectoryToSegmentDirectories(ctx, req.(*CopyMasterDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StopAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StopAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/StopAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StopAgent(ctx, req.(*StopAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idl.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUpgradeStatus",
			Handler:    _Agent_CheckUpgradeStatus_Handler,
		},
		{
			MethodName: "CheckConversionStatus",
			Handler:    _Agent_CheckConversionStatus_Handler,
		},
		{
			MethodName: "CheckDiskSpace",
			Handler:    _Agent_CheckDiskSpace_Handler,
		},
		{
			MethodName: "AgentExecuteUpgradePrimariesSubStep",
			Handler:    _Agent_AgentExecuteUpgradePrimariesSubStep_Handler,
		},
		{
			MethodName: "CreateSegmentDataDirectories",
			Handler:    _Agent_CreateSegmentDataDirectories_Handler,
		},
		{
			MethodName: "CopyMasterDirectoryToSegmentDirectories",
			Handler:    _Agent_CopyMasterDirectoryToSegmentDirectories_Handler,
		},
		{
			MethodName: "StopAgent",
			Handler:    _Agent_StopAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub_to_agent.proto",
}

func init() { proto.RegisterFile("hub_to_agent.proto", fileDescriptor_hub_to_agent_8d1ee2dffad95038) }

var fileDescriptor_hub_to_agent_8d1ee2dffad95038 = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x25, 0x6d, 0x02, 0xc9, 0x0d, 0xaa, 0xa2, 0xa1, 0x55, 0x5c, 0x37, 0x2a, 0xc1, 0x2c, 0xe8,
	0x02, 0x65, 0x51, 0xd8, 0x54, 0xac, 0x20, 0x41, 0x2a, 0x52, 0x69, 0x23, 0xa7, 0x65, 0x87, 0xaa,
	0x49, 0x7c, 0x69, 0x46, 0x75, 0x3c, 0x66, 0x3c, 0xa1, 0xe4, 0x5b, 0xf8, 0x04, 0xbe, 0x8c, 0xbf,
	0x40, 0xf3, 0x72, 0x9d, 0xd4, 0xee, 0x2e, 0xf7, 0x9c, 0xfb, 0x9a, 0x33, 0x67, 0x1c, 0x20, 0xf3,
	0xe5, 0xf4, 0x5a, 0xf2, 0x6b, 0x7a, 0x83, 0x89, 0x1c, 0xa4, 0x82, 0x4b, 0x4e, 0xb6, 0x59, 0x14,
	0xfb, 0x9d, 0x59, 0xcc, 0x14, 0x31, 0x5f, 0x4e, 0x0d, 0x1c, 0xfc, 0xad, 0x41, 0xf7, 0x2a, 0xbd,
	0x11, 0x34, 0xc2, 0xb1, 0x60, 0x0b, 0x2a, 0x18, 0x66, 0x21, 0xfe, 0x5c, 0x62, 0x26, 0x49, 0x0f,
	0x5a, 0x17, 0x71, 0xf4, 0x89, 0x25, 0x23, 0x26, 0xbc, 0x5a, 0xbf, 0x76, 0xd4, 0x0a, 0xef, 0x01,
	0xc5, 0x9e, 0xe3, 0x9d, 0x65, 0xb7, 0x0c, 0x9b, 0x03, 0xe4, 0x10, 0xe0, 0x1c, 0xef, 0xbe, 0xa1,
	0xc8, 0x18, 0x4f, 0xbc, 0x6d, 0x4d, 0x17, 0x10, 0xf2, 0x1e, 0x9e, 0x8f, 0xa8, 0xa4, 0x23, 0x26,
	0xc6, 0x94, 0x89, 0xcc, 0xab, 0xf7, 0xb7, 0x8f, 0xda, 0xc7, 0x9d, 0x01, 0x8b, 0xe2, 0x41, 0x81,
	0x08, 0xd7, 0xb2, 0x82, 0x3f, 0x35, 0x68, 0x17, 0x00, 0x35, 0xe5, 0x22, 0x8e, 0x2c, 0x62, 0x57,
	0x2c, 0x20, 0x76, 0x0b, 0xc7, 0x6f, 0xe5, 0x5b, 0x38, 0xde, 0x83, 0x67, 0x17, 0x71, 0x34, 0xe6,
	0x42, 0xea, 0x15, 0x1b, 0xa1, 0x0b, 0x15, 0x73, 0x8e, 0x77, 0x9a, 0xa9, 0x1b, 0xc6, 0x86, 0x8a,
	0x19, 0xf2, 0x44, 0x62, 0x22, 0xbd, 0x86, 0x61, 0x6c, 0x18, 0x74, 0x61, 0xef, 0xa1, 0x94, 0x69,
	0xbc, 0x0a, 0x0e, 0x60, 0x7f, 0x38, 0xc7, 0xd9, 0xad, 0x65, 0x27, 0x92, 0xca, 0xa5, 0x53, 0x39,
	0xf8, 0x00, 0xdd, 0x32, 0x32, 0x8d, 0x57, 0xa4, 0x0f, 0xed, 0xb1, 0xe0, 0x33, 0xcc, 0xb2, 0x33,
	0x96, 0x49, 0x7b, 0xbe, 0x22, 0x14, 0xcc, 0xa1, 0xa7, 0x8b, 0x87, 0x3c, 0xf9, 0x65, 0x94, 0x5d,
	0x6b, 0x4e, 0xde, 0x42, 0x73, 0x82, 0x37, 0x0b, 0x4c, 0x64, 0xe6, 0xd5, 0x0a, 0x12, 0x5b, 0xf0,
	0x4b, 0xf2, 0x83, 0x87, 0x79, 0x06, 0xf1, 0xa1, 0x79, 0xca, 0x33, 0x99, 0xd0, 0x05, 0x5a, 0xb1,
	0xf2, 0x38, 0xb8, 0x82, 0x76, 0xa1, 0xa8, 0xa8, 0x42, 0x6d, 0x4d, 0x05, 0x42, 0xa0, 0x3e, 0x9a,
	0xb2, 0x48, 0x37, 0x68, 0x84, 0xfa, 0xb7, 0xca, 0x76, 0x97, 0x60, 0xac, 0xe0, 0xc2, 0xe0, 0x0c,
	0xfc, 0x8a, 0x03, 0x28, 0x01, 0x06, 0xd0, 0x34, 0x21, 0xba, 0xf5, 0x89, 0x5e, 0xdf, 0xe8, 0xbb,
	0xb2, 0xa9, 0x79, 0x4e, 0x70, 0x02, 0x07, 0x43, 0x81, 0x54, 0xa2, 0x5d, 0xd5, 0x4e, 0x71, 0x6a,
	0xf8, 0xd0, 0x8c, 0xa8, 0xa4, 0x91, 0x32, 0x9c, 0x6a, 0xd7, 0x0a, 0xf3, 0x58, 0xdf, 0x51, 0x69,
	0xa9, 0xba, 0xc0, 0x31, 0xec, 0x0e, 0x79, 0xba, 0xfa, 0x4a, 0x33, 0x89, 0xa2, 0xd0, 0xb0, 0x07,
	0xad, 0x85, 0xc3, 0xdc, 0x0b, 0xc9, 0x81, 0xb5, 0x71, 0x5b, 0x1b, 0xe3, 0x76, 0x81, 0x6c, 0x74,
	0x54, 0x73, 0x08, 0x74, 0x26, 0x92, 0xa7, 0x1f, 0xd5, 0xbb, 0x75, 0xfe, 0xe8, 0xc0, 0x4e, 0x01,
	0x4b, 0xe3, 0xd5, 0xf1, 0xbf, 0x3a, 0x34, 0x74, 0x48, 0x2e, 0x81, 0x3c, 0xf4, 0x0e, 0x39, 0xd4,
	0x1a, 0x55, 0x3a, 0xce, 0xef, 0x55, 0xf2, 0x6a, 0x87, 0x27, 0xe4, 0x3b, 0xec, 0x95, 0xde, 0x09,
	0x79, 0x75, 0x5f, 0x58, 0x61, 0x38, 0xff, 0xe5, 0x63, 0x29, 0xa6, 0xfd, 0x29, 0xec, 0x68, 0x7e,
	0xc4, 0xb2, 0xdb, 0x49, 0x4a, 0x67, 0x48, 0xfc, 0xfb, 0xa2, 0x1c, 0x74, 0x0d, 0xbd, 0x52, 0xce,
	0x74, 0xa2, 0xf0, 0x5a, 0xeb, 0xf0, 0xf9, 0x37, 0xce, 0x96, 0x12, 0x37, 0x1f, 0xdf, 0x64, 0x39,
	0x9d, 0x48, 0x4c, 0x89, 0x39, 0x6f, 0xc5, 0x57, 0xce, 0xf7, 0x2b, 0x58, 0x33, 0x62, 0x0a, 0xbd,
	0x32, 0x5b, 0xe0, 0x4c, 0x72, 0x95, 0x46, 0xfa, 0x66, 0xbd, 0x6a, 0xd3, 0xf9, 0x87, 0x8f, 0x64,
	0x98, 0x19, 0xd7, 0xf0, 0x66, 0xcd, 0x0b, 0xba, 0xf9, 0xea, 0x92, 0xbb, 0xec, 0xc2, 0xb8, 0x7d,
	0xd3, 0xac, 0xc4, 0x8b, 0x7e, 0xb7, 0x8c, 0x32, 0x03, 0x4e, 0xa0, 0x95, 0x5b, 0x88, 0xec, 0x99,
	0x0f, 0xc0, 0x86, 0xcd, 0xfc, 0x17, 0x9b, 0xb0, 0x2e, 0x9d, 0x3e, 0xd5, 0x7f, 0x13, 0xef, 0xfe,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xfd, 0x4f, 0xc3, 0x53, 0x06, 0x00, 0x00,
}
